### ISSUE TITLE
Old url in about section

### ISSUE THREAD

**Issue by web2033** [vueuse/vueuse-vite-starter#2]
Hi. Repo's URL points to an old example...

**Comment by antfu** [comment]
Would you like to create a PR for it? Thanks.

**Comment by web2033** [comment]
Not possible - I meant this part:
![2021-02-04_004251](https://user-images.githubusercontent.com/11320080/106819072-f3153600-6681-11eb-8fe3-296455ddd619.png)

**Comment by antfu** [comment]
Oh, thank you, fixed!
